import {createRoutine} from "redux-saga-routines";

// <--- SAVE ALL ---->
const SAVE_ALL_DATA = createRoutine("SAVE_ALL")
// <--- SAVE ALL ---->


// <--- PROFILE --->
const CHANGE_MODE = createRoutine("CHANGE_MODE");
const CHANGE_LANG = createRoutine("CHANGE_LANG");
const GET_TRANSLATIONS = createRoutine("GET_TRANSLATIONS");

// <--- PROFILE --->

// <--- STRUCTURE CONTROLLER --->
const STRUCTURE_CONTROLLER_CREATE = createRoutine(
    "STRUCTURE_CONTROLLER_CREATE"
);
const STRUCTURE_CONTROLLER_UPDATE = createRoutine(
    "STRUCTURE_CONTROLLER_UPDATE"
);
const STRUCTURE_CONTROLLER_DELETE = createRoutine(
    "STRUCTURE_CONTROLLER_DELETE"
);
const STRUCTURE_CONTROLLER_HIERARCHY_BY_ALT_ABS_CODE = createRoutine(
    "STRUCTURE_CONTROLLER_HIERARCHY_BY_ALT_ABS_CODE"
);
// <--- STRUCTURE CONTROLLER --->

// <--- STRUCTURE RELATION CONTROLLER --->
const STRUCTURE_RELATION_CONTROLLER_CREATE = createRoutine(
    "STRUCTURE_RELATION_CONTROLLER_CREATE"
);
const STRUCTURE_RELATION_CONTROLLER_DELETE = createRoutine(
    "STRUCTURE_RELATION_CONTROLLER_DELETE"
);
// <--- STRUCTURE RELATION CONTROLLER --->

// <--- STRUCTURE TYPE CONTROLLER  --->
const STRUCTURE_TYPE_CONTROLLER_CREATE = createRoutine(
    "STRUCTURE_TYPE_CONTROLLER_CREATE"
);
const STRUCTURE_TYPE_CONTROLLER_UPDATE = createRoutine(
    "STRUCTURE_TYPE_CONTROLLER_UPDATE"
);
const STRUCTURE_TYPE_CONTROLLER_DELETE = createRoutine(
    "STRUCTURE_TYPE_CONTROLLER_DELETE"
);
// <--- STRUCTURE TYPE CONTROLLER --->

// <--- TEMPLATE DOCUMENT CONTROLLER --->
const TEMPLATE_DOCUMENT_CONTROLLER_CREATE = createRoutine(
    "TEMPLATE_DOCUMENT_CONTROLLER_CREATE"
);
const TEMPLATE_DOCUMENT_CONTROLLER_UPDATE = createRoutine(
    "TEMPLATE_DOCUMENT_CONTROLLER_UPDATE"
);
const TEMPLATE_DOCUMENT_CONTROLLER_DELETE = createRoutine(
    "TEMPLATE_DOCUMENT_CONTROLLER_DELETE"
);
const TEMPLATE_DOCUMENT_CONTROLLER_SYNC = createRoutine(
    "TEMPLATE_DOCUMENT_CONTROLLER_SYNC"
);
// <--- TEMPLATE DOCUMENT CONTROLLER --->

// <--- TEMPLATE DOCUMENT CUSTOM VAR CONTROLLER --->
const TEMPLATE_DOCUMENT_CUSTOM_VAR_CONTROLLER_CREATE = createRoutine(
    "TEMPLATE_DOCUMENT_CUSTOM_VAR_CONTROLLER_CREATE"
);
const TEMPLATE_DOCUMENT_CUSTOM_VAR_CONTROLLER_UPDATE = createRoutine(
    "TEMPLATE_DOCUMENT_CUSTOM_VAR_CONTROLLER_UPDATE"
);
const TEMPLATE_DOCUMENT_CUSTOM_VAR_CONTROLLER_DELETE = createRoutine(
    "TEMPLATE_DOCUMENT_CUSTOM_VAR_CONTROLLER_DELETE"
);
// <--- TEMPLATE DOCUMENT CUSTOM VAR CONTROLLER --->

// <--- USER CONTROLLER --->
const USER_CONTROLLER_CHANGE_PASSWORD = createRoutine(
    "USER_CONTROLLER_CHANGE_PASSWORD"
);
const USER_CONTROLLER_CHECK_CONVICTED = createRoutine(
    "USER_CONTROLLER_CHECK_CONVICTED"
);
const USER_CONTROLLER_EMPLOYEE_INFORMATION_DATA = createRoutine(
    "USER_CONTROLLER_EMPLOYEE_INFORMATION_DATA"
);
const USER_CONTROLLER_EMPLOYEE_INFORMATION_REQUEST = createRoutine(
    "USER_CONTROLLER_EMPLOYEE_INFORMATION_REQUEST"
);
const USER_CONTROLLER_RECHECK_CONVICTED = createRoutine(
    "USER_CONTROLLER_RECHECK_CONVICTED"
);
// <--- USER CONTROLLER --->

// <--- SERVICES CONTROLLER --->
const SERVICES_CONTROLLER_SYNC_FIDO_SERVICE = createRoutine(
    "SERVICES_CONTROLLER_SYNC_FIDO_SERVICE"
);
const SERVICES_CONTROLLER_SYNC_POSITION_CURRENT = createRoutine(
    "SERVICES_CONTROLLER_SYNC_POSITION_CURRENT"
);
const SERVICES_CONTROLLER_SYNC_POSITION_HISTORY = createRoutine(
    "SERVICES_CONTROLLER_SYNC_POSITION_HISTORY"
);
const SERVICES_CONTROLLER_SYNC_REGISTRATION_INDIVIDUAL_SERVICE = createRoutine(
    "SERVICES_CONTROLLER_SYNC_REGISTRATION_INDIVIDUAL_SERVICE"
);
const SERVICES_CONTROLLER_SYNC_TAX_TIN_SERVICE = createRoutine(
    "SERVICES_CONTROLLER_SYNC_TAX_TIN_SERVICE"
);
// <--- SERVICES CONTROLLER --->

// <--- LANGUAGE CONTROLLER --->
const LANGUAGE_CONTROLLER_UPDATE = createRoutine("LANGUAGE_CONTROLLER_UPDATE");
// <--- LANGUAGE CONTROLLER --->

// <--- COUNTRY CONTROLLER --->
const COUNTRY_CONTROLLER_CREATE = createRoutine("COUNTRY_CONTROLLER_CREATE");
const COUNTRY_CONTROLLER_UPDATE = createRoutine("COUNTRY_CONTROLLER_UPDATE");
const COUNTRY_CONTROLLER_DELETE = createRoutine("COUNTRY_CONTROLLER_DELETE");
// <--- COUNTRY CONTROLLER --->

// <--- GSP COUNTRY CONTROLLER --->
const GSP_COUNTRY_CONTROLLER_CREATE = createRoutine(
    "GSP_COUNTRY_CONTROLLER_CREATE"
);
const GSP_COUNTRY_CONTROLLER_UPDATE = createRoutine(
    "GSP_COUNTRY_CONTROLLER_UPDATE"
);
const GSP_COUNTRY_CONTROLLER_DELETE = createRoutine(
    "GSP_COUNTRY_CONTROLLER_DELETE"
);
// <--- GSP COUNTRY CONTROLLER --->

// <--- REGION CONTROLLER --->
const REGION_CONTROLLER_CREATE = createRoutine("REGION_CONTROLLER_CREATE");
const REGION_CONTROLLER_UPDATE = createRoutine("REGION_CONTROLLER_UPDATE");
const REGION_CONTROLLER_DELETE = createRoutine("REGION_CONTROLLER_DELETE");
// <--- REGION CONTROLLER --->

// <--- GSP REGION CONTROLLER --->
const GSP_REGION_CONTROLLER_CREATE = createRoutine(
    "GSP_REGION_CONTROLLER_CREATE"
);
const GSP_REGION_CONTROLLER_UPDATE = createRoutine(
    "GSP_REGION_CONTROLLER_UPDATE"
);
const GSP_REGION_CONTROLLER_DELETE = createRoutine(
    "GSP_REGION_CONTROLLER_DELETE"
);
// <--- GSP REGION CONTROLLER --->

// <--- DISTRICT CONTROLLER --->
const DISTRICT_CONTROLLER_CREATE = createRoutine("DISTRICT_CONTROLLER_CREATE");
const DISTRICT_CONTROLLER_UPDATE = createRoutine("DISTRICT_CONTROLLER_UPDATE");
const DISTRICT_CONTROLLER_DELETE = createRoutine("DISTRICT_CONTROLLER_DELETE");
// <--- DISTRICT CONTROLLER --->

// <--- GSP DISTRICT CONTROLLER --->
const GSP_DISTRICT_CONTROLLER_CREATE = createRoutine(
    "GSP_DISTRICT_CONTROLLER_CREATE"
);
const GSP_DISTRICT_CONTROLLER_UPDATE = createRoutine(
    "GSP_DISTRICT_CONTROLLER_UPDATE"
);
const GSP_DISTRICT_CONTROLLER_DELETE = createRoutine(
    "GSP_DISTRICT_CONTROLLER_DELETE"
);
// <--- GSP DISTRICT CONTROLLER --->

// <--- PARTY CONTROLLER --->
const PARTY_CONTROLLER_CREATE = createRoutine("PARTY_CONTROLLER_CREATE");
const PARTY_CONTROLLER_UPDATE = createRoutine("PARTY_CONTROLLER_UPDATE");
const PARTY_CONTROLLER_DELETE = createRoutine("PARTY_CONTROLLER_DELETE");
// <--- PARTY CONTROLLER --->

// <--- NATIONALITY CONTROLLER --->
const NATIONALITY_CONTROLLER_CREATE = createRoutine(
    "NATIONALITY_CONTROLLER_CREATE"
);
const NATIONALITY_CONTROLLER_UPDATE = createRoutine(
    "NATIONALITY_CONTROLLER_UPDATE"
);
const NATIONALITY_CONTROLLER_DELETE = createRoutine(
    "NATIONALITY_CONTROLLER_DELETE"
);
// <--- NATIONALITY CONTROLLER --->

// <--- GSP NATIONALITY CONTROLLER --->
const GSP_NATIONALITY_CONTROLLER_CREATE = createRoutine(
    "GSP_NATIONALITY_CONTROLLER_CREATE"
);
const GSP_NATIONALITY_CONTROLLER_UPDATE = createRoutine(
    "GSP_NATIONALITY_CONTROLLER_UPDATE"
);
const GSP_NATIONALITY_CONTROLLER_DELETE = createRoutine(
    "GSP_NATIONALITY_CONTROLLER_DELETE"
);
// <--- GSP NATIONALITY CONTROLLER --->

// <--- STAFF CONTROLLER --->
const STAFF_CONTROLLER_CREATE = createRoutine("STAFF_CONTROLLER_CREATE");
const STAFF_CONTROLLER_UPDATE = createRoutine("STAFF_CONTROLLER_UPDATE");
const STAFF_CONTROLLER_DELETE = createRoutine("STAFF_CONTROLLER_DELETE");
const STAFF_CONTROLLER_CLOSE = createRoutine("STAFF_CONTROLLER_CLOSE");
// <--- STAFF CONTROLLER --->

// <--- POSITION CONTROLLER --->
const POSITION_CONTROLLER_CREATE = createRoutine("POSITION_CONTROLLER_CREATE");
const POSITION_CONTROLLER_UPDATE = createRoutine("POSITION_CONTROLLER_UPDATE");
const POSITION_CONTROLLER_DELETE = createRoutine("POSITION_CONTROLLER_DELETE");
// <--- POSITION CONTROLLER --->

// <--- I ABS CONTROLLER --->
const IABS_CONTROLLER_BANKS = createRoutine("IABS_CONTROLLER_BANKS");
const IABS_TRANSFORM = createRoutine("IABS_TRANSFORM");
const IABS_TRANSFORM_REMOVE = createRoutine("IABS_TRANSFORM_REMOVE");
const IABS_TRANSFORM_UPDATE = createRoutine("IABS_TRANSFORM_UPDATE");
// <--- I ABS CONTROLLER --->

// <--- EMPLOYEE INFORMATION --->
const EMPLOYEE_INFORMATION_DATA = createRoutine("EMPLOYEE_INFORMATION_DATA");
const EMPLOYEE_INFORMATION_REQUEST = createRoutine(
    "EMPLOYEE_INFORMATION_REQUEST"
);
const EMPLOYEE_POSITION_PROFILE_INFO_SET = createRoutine(
    "EMPLOYEE_POSITION_PROFILE_INFO_SET"
);
// <--- EMPLOYEE INFORMATION --->

// <--- IABS LINK --->>
const LINK_ABS_COUNTRY_TO_CORE_COUNTRY = createRoutine(
    "LINK_ABS_COUNTRY_TO_CORE_COUNTRY"
);
const LINK_ABS_DISTRICT_TO_CORE_DISTRICT = createRoutine(
    "LINK_ABS_DISTRICT_TO_CORE_DISTRICT"
);
const LINK_ABS_NATION_TO_CORE_NATIONALITY = createRoutine(
    "LINK_ABS_NATION_TO_CORE_NATIONALITY"
);
const LINK_ABS_PARTY_TO_CORE_PARTY = createRoutine(
    "LINK_ABS_PARTY_TO_CORE_PARTY"
);
const LINK_ABS_REGION_TO_CORE_REGION = createRoutine(
    "LINK_ABS_REGION_TO_CORE_REGION"
);
const LINK_ABS_POSITION_TO_CORE_POSITION = createRoutine(
    "LINK_ABS_POSITION_TO_CORE_POSITION"
);

// <--- IABS LINK --->>

// <--- IABS LOAD --->
const IABS_LOAD_COUNTRIES = createRoutine("IABS_LOAD_COUNTRIES");
const IABS_LOAD_DISTRICTS = createRoutine("IABS_LOAD_DISTRICTS");
const IABS_LOAD_NATIONS = createRoutine("IABS_LOAD_NATIONS");
const IABS_LOAD_PARTIES = createRoutine("IABS_LOAD_PARTIES");
const IABS_LOAD_REGIONS = createRoutine("IABS_LOAD_REGIONS");
// <--- IABS LOAD --->

// <--- DIPLOMA QUALIFICATION --->
const DIPLOMA_QUALIFICATION_CREATE = createRoutine(
    "DIPLOMA_QUALIFICATION_CREATE"
);
const DIPLOMA_QUALIFICATION_UPDATE = createRoutine(
    "DIPLOMA_QUALIFICATION_UPDATE"
);
const DIPLOMA_QUALIFICATION_DELETE = createRoutine(
    "DIPLOMA_QUALIFICATION_DELETE"
);
// <--- DIPLOMA QUALIFICATION --->

// <--- EDUCATIONAL INSTITUTION --->
const EDUCATIONAL_INSTITUTION_CREATE = createRoutine(
    "EDUCATIONAL_INSTITUTION_CREATE"
);
const EDUCATIONAL_INSTITUTION_UPDATE = createRoutine(
    "EDUCATIONAL_INSTITUTION_UPDATE"
);
const EDUCATIONAL_INSTITUTION_DELETE = createRoutine(
    "EDUCATIONAL_INSTITUTION_DELETE"
);
// <--- DIPLOMA QUALIFICATION --->

// <--- FACULTY --->
const FACULTY_CREATE = createRoutine("FACULTY_CREATE");
const FACULTY_UPDATE = createRoutine("FACULTY_UPDATE");
const FACULTY_DELETE = createRoutine("FACULTY_DELETE");
// <--- FACULTY --->

// <--- FORM STUDY --->
const FORM_STUDY_CREATE = createRoutine("FORM_STUDY_CREATE");
const FORM_STUDY_UPDATE = createRoutine("FORM_STUDY_UPDATE");
const FORM_STUDY_DELETE = createRoutine("FORM_STUDY_DELETE");
// <--- FORM STUDY --->

// <--- RELATIVES --->
const RELATIVES_CREATE = createRoutine("RELATIVES_CREATE");
const RELATIVES_UPDATE = createRoutine("RELATIVES_UPDATE");
const RELATIVES_DELETE = createRoutine("RELATIVES_DELETE");
// <--- RELATIVES --->

// <--- SPECIALITY --->
const SPECIALITY_CREATE = createRoutine("SPECIALITY_CREATE");
const SPECIALITY_UPDATE = createRoutine("SPECIALITY_UPDATE");
const SPECIALITY_DELETE = createRoutine("SPECIALITY_DELETE");
// <--- SPECIALITY --->

// <--- COMPANY --->
const COMPANY_CREATE = createRoutine("COMPANY_CREATE");
const COMPANY_UPDATE = createRoutine("COMPANY_UPDATE");
const COMPANY_DELETE = createRoutine("COMPANY_DELETE");
// <--- COMPANY --->

// <--- EDUCATION --->
const EDUCATION_CREATE = createRoutine("EDUCATION_CREATE");
const EDUCATION_CREATE_BY_USER = createRoutine("EDUCATION_CREATE_BY_USER");
const EDUCATION_UPDATE = createRoutine("EDUCATION_UPDATE");
const EDUCATION_DELETE = createRoutine("EDUCATION_DELETE");
// <--- EDUCATION --->

// <--- TASKS --->
const GET_FORMS_WITH_FIELDS = createRoutine("GET_FORMS_WITH_FIELDS");
const TASKS_USER_FORM_SET_VALUES_AND_RETURN_VALUES = createRoutine("TASKS_USER_FORM_SET_VALUES_AND_RETURN_VALUES");
const TASKS_USER_FORM_SET_VALUES_AND_RETURN_VALUES_COMPLETE = createRoutine("TASKS_USER_FORM_SET_VALUES_AND_RETURN_VALUES_COMPLETE");
// <--- TASKS --->


// <--- EMPLOYEE_REGISTER --->
const EMPLOYEE_REGISTER_REQUEST_CREATE = createRoutine("EMPLOYEE_REGISTER_REQUEST_CREATE");
const EMPLOYEE_REGISTER_REQUEST_UPDATE = createRoutine("EMPLOYEE_REGISTER_REQUEST_UPDATE");
const EMPLOYEE_REGISTER_REQUEST_DELETE = createRoutine("EMPLOYEE_REGISTER_REQUEST_DELETE");
const EMPLOYEE_REQUEST_CONFIRM = createRoutine("EMPLOYEE_REQUEST_CONFIRM");
// <--- EMPLOYEE_REGISTER --->

// <--- DOCUMENT --->
const CREATE_NEW_DOCUMENT = createRoutine("CREATE_NEW_DOCUMENT");
// <--- DOCUMENT --->

// <--- RECRUITMENT --->
const CREATE_RECRUITMENT = createRoutine("CREATE_RECRUITMENT");
// <--- RECRUITMENT --->

// <--- EMPLOYEE -->>
const EMPLOYEE_CREATE = createRoutine("EMPLOYEE_CREATE")
const EMPLOYEE_UPDATE = createRoutine("EMPLOYEE_UPDATE");
const EMPLOYEE_DELETE = createRoutine("EMPLOYEE_DELETE");
const EMPLOYEE_CREATE_BY_DOCUMENT = createRoutine("EMPLOYEE_CREATE_BY_DOCUMENT");
const EMPLOYEE_REFRESH_SERVICES_DATA = createRoutine("EMPLOYEE_REFRESH_SERVICES_DATA");

const EMPLOYEE_EDUCATION_CREATE = createRoutine("EMPLOYEE_EDUCATION_CREATE");
const EMPLOYEE_EDUCATION_UPDATE = createRoutine("EMPLOYEE_EDUCATION_UPDATE");
const EMPLOYEE_EDUCATION_DELETE = createRoutine("EMPLOYEE_EDUCATION_DELETE");

const EMPLOYEE_RELATION_CREATE = createRoutine("EMPLOYEE_RELATION_CREATE");
const EMPLOYEE_RELATION_UPDATE = createRoutine("EMPLOYEE_RELATION_CREATE");
const EMPLOYEE_RELATION_DELETE = createRoutine("EMPLOYEE_RELATION_CREATE");
// <--- EMPLOYEE -->>

// <--- STRUCTURE VERSION --->
const CREATE_STRUCTURE_VERSION = createRoutine("CREATE_STRUCTURE_VERSION");
// <--- STRUCTURE VERSION --->

// <--- STRUCTURE CHANGE HIERARCHY VERSION --->
const STRUCTURE_CHANGE_HIERARCHY = createRoutine("STRUCTURE_CHANGE_HIERARCHY");
// <--- STRUCTURE VERSION --->

// <--- STRUCTURE_LINK_BATCH--->
const STRUCTURE_LINK_BATCH = createRoutine("STRUCTURE_LINK_BATCH");
// <--- STRUCTURE_LINK_BATCH --->


// <--- EMPLOYEE RELATIVES --->
const EMPLOYEE_RELATIVES_CREATE = createRoutine("EMPLOYEE_RELATIVES_CREATE");
const EMPLOYEE_RELATIVES_UPDATE = createRoutine("EMPLOYEE_RELATIVES_UPDATE");
const EMPLOYEE_RELATIVES_DELETE = createRoutine("EMPLOYEE_RELATIVES_DELETE");
// <--- EMPLOYEE RELATIVES --->


// <--- STRUCTURE_ABS_SYNC--->
const STRUCTURE_ABS_SYNC = createRoutine("STRUCTURE_ABS_SYNC");
const CREATE_STRUCTURE = createRoutine("CREATE_STRUCTURE");
// <--- STRUCTURE_ABS_SYNC --->
// <--- STRUCTURE_ABS_SYNC--->
const STRUCTURE_ABS_SYNC_FILIALS = createRoutine("STRUCTURE_ABS_SYNC_FILIALS");
// <--- STRUCTURE_ABS_SYNC --->
const RELOAD_EMPLOYEE_PROFILE_PHOTO = createRoutine("RELOAD_EMPLOYEE_PROFILE_PHOTO");
const RELOAD_EMPLOYEE_INFO_FROM_IABS = createRoutine("RELOAD_EMPLOYEE_INFO_FROM_IABS");
const ASYNC_VACCINE_CERTIFICATE = createRoutine("ASYNC_VACCINE_CERTIFICATE");
const ASYNC_EMPLOYEE_RELATIVES = createRoutine("ASYNC_EMPLOYEE_RELATIVES");
const ASYNC_EMPLOYEE_CONVICTION = createRoutine("ASYNC_EMPLOYEE_CONVICTION");
const ASYNC_EMPLOYEE_PSYCHO_INFO = createRoutine("ASYNC_EMPLOYEE_PSYCHO_INFO");
const ASYNC_EMPLOYEE_NARCO_INFO = createRoutine("ASYNC_EMPLOYEE_NARCO_INFO");
const ASYNC_EMPLOYEE_CV = createRoutine("ASYNC_EMPLOYEE_CV");
const ASYNC_WORK_REFERENCE = createRoutine("ASYNC_WORK_REFERENCE");

const SET_STRUCTURE_TYPE_CHILD_ALL = createRoutine("SET_STRUCTURE_TYPE_CHILD_ALL");
const SET_STRUCTURE_HIERARCHY_AS_TEMPLATE = createRoutine("SET_STRUCTURE_HIERARCHY_AS_TEMPLATE");


// BUSINESS-PROCESS
const BUSINESS_PROCESS_CREATE = createRoutine("BUSINESS_PROCESS_CREATE")
const BUSINESS_PROCESS_UPDATE = createRoutine("BUSINESS_PROCESS_UPDATE")
const BUSINESS_PROCESS_DELETE = createRoutine("BUSINESS_PROCESS_DELETE")
// BUSINESS-PROCESS

// DOCUMENT PROCESS
const DOCUMENT_PROCESS_CREATE = createRoutine("DOCUMENT_PROCESS_CREATE")
const DOCUMENT_SIGN_PROCESS = createRoutine("DOCUMENT_SIGN_PROCESS")
const DOCUMENT_SIGN_WITH_EIMZO_PROCESS = createRoutine("DOCUMENT_SIGN_WITH_EIMZO_PROCESS")
// DOCUMENT PROCESS


// VACANCY PROCESS
const VACANCY_PROCESS_START = createRoutine("VACANCY_PROCESS_START")
// VACANCY PROCESS

const POST_UPDATE_STRUCTURE = createRoutine("POST_UPDATE_STRUCTURE")

// VACATION GRAPHIC
const VACATION_GRAPHIC_START = createRoutine("VACATION_GRAPHIC_START")
// VACATION GRAPHIC

// EXCEPTION DAY
const SET_EXCEPTION_DAY = createRoutine("SET_EXCEPTION_DAY")
const UPDATE_EXCEPTION_DAY = createRoutine("UPDATE_EXCEPTION_DAY")
const DELETE_EXCEPTION_DAY = createRoutine("DELETE_EXCEPTION_DAY")
// EXCEPTION DAY

// DOCUMENT REQUESTS
const CREATE_AND_START_NEW_PROCESS = createRoutine("CREATE_AND_START_NEW_PROCESS")
const GENERATE_DOCS = createRoutine("GENERATE_DOCS")
// DOCUMENT REQUESTS

const UPLOAD_EMPLOYEE_FILE = createRoutine("UPLOAD_EMPLOYEE_FILE")
const UPLOAD_CANDIDATE_FILE = createRoutine("UPLOAD_CANDIDATE_FILE")

// TEMPLATE DOCUMENT CUSTOM VAR STRUCTURE
const TEMPLATE_DOCUMENT_CUSTOM_VAR_STRUCTURE = createRoutine("TEMPLATE_DOCUMENT_CUSTOM_VAR_STRUCTURE")
//  TEMPLATE DOCUMENT CUSTOM VAR STRUCTURE


// MIGRATE FILIAL DATA
const MIGRATE_FILIAL_DATA = createRoutine("MIGRATE_FILIAL_DATA")
//  MIGRATE FILIAL DATA


export default {
    SAVE_ALL_DATA,
    CHANGE_MODE,
    CHANGE_LANG,
    GET_TRANSLATIONS,
    STRUCTURE_CONTROLLER_CREATE,
    STRUCTURE_CONTROLLER_UPDATE,
    STRUCTURE_CONTROLLER_DELETE,
    STRUCTURE_CONTROLLER_HIERARCHY_BY_ALT_ABS_CODE,
    STRUCTURE_RELATION_CONTROLLER_CREATE,
    STRUCTURE_RELATION_CONTROLLER_DELETE,
    STRUCTURE_TYPE_CONTROLLER_CREATE,
    STRUCTURE_TYPE_CONTROLLER_UPDATE,
    STRUCTURE_TYPE_CONTROLLER_DELETE,
    TEMPLATE_DOCUMENT_CONTROLLER_CREATE,
    TEMPLATE_DOCUMENT_CONTROLLER_UPDATE,
    TEMPLATE_DOCUMENT_CONTROLLER_DELETE,
    TEMPLATE_DOCUMENT_CONTROLLER_SYNC,
    TEMPLATE_DOCUMENT_CUSTOM_VAR_CONTROLLER_CREATE,
    TEMPLATE_DOCUMENT_CUSTOM_VAR_CONTROLLER_UPDATE,
    TEMPLATE_DOCUMENT_CUSTOM_VAR_CONTROLLER_DELETE,
    USER_CONTROLLER_CHANGE_PASSWORD,
    USER_CONTROLLER_CHECK_CONVICTED,
    USER_CONTROLLER_EMPLOYEE_INFORMATION_DATA,
    USER_CONTROLLER_EMPLOYEE_INFORMATION_REQUEST,
    USER_CONTROLLER_RECHECK_CONVICTED,
    SERVICES_CONTROLLER_SYNC_FIDO_SERVICE,
    SERVICES_CONTROLLER_SYNC_POSITION_CURRENT,
    SERVICES_CONTROLLER_SYNC_POSITION_HISTORY,
    SERVICES_CONTROLLER_SYNC_REGISTRATION_INDIVIDUAL_SERVICE,
    SERVICES_CONTROLLER_SYNC_TAX_TIN_SERVICE,
    LANGUAGE_CONTROLLER_UPDATE,
    IABS_CONTROLLER_BANKS,
    IABS_TRANSFORM,
    IABS_TRANSFORM_REMOVE,
    EMPLOYEE_INFORMATION_DATA,
    EMPLOYEE_INFORMATION_REQUEST,
    EMPLOYEE_POSITION_PROFILE_INFO_SET,
    IABS_TRANSFORM_UPDATE,
    COUNTRY_CONTROLLER_CREATE,
    COUNTRY_CONTROLLER_UPDATE,
    COUNTRY_CONTROLLER_DELETE,
    REGION_CONTROLLER_CREATE,
    REGION_CONTROLLER_UPDATE,
    REGION_CONTROLLER_DELETE,
    GSP_COUNTRY_CONTROLLER_CREATE,
    GSP_COUNTRY_CONTROLLER_UPDATE,
    GSP_COUNTRY_CONTROLLER_DELETE,
    GSP_REGION_CONTROLLER_CREATE,
    GSP_REGION_CONTROLLER_UPDATE,
    GSP_REGION_CONTROLLER_DELETE,
    DISTRICT_CONTROLLER_CREATE,
    DISTRICT_CONTROLLER_UPDATE,
    DISTRICT_CONTROLLER_DELETE,
    GSP_DISTRICT_CONTROLLER_CREATE,
    GSP_DISTRICT_CONTROLLER_UPDATE,
    GSP_DISTRICT_CONTROLLER_DELETE,
    PARTY_CONTROLLER_CREATE,
    PARTY_CONTROLLER_UPDATE,
    PARTY_CONTROLLER_DELETE,
    NATIONALITY_CONTROLLER_CREATE,
    NATIONALITY_CONTROLLER_UPDATE,
    NATIONALITY_CONTROLLER_DELETE,
    GSP_NATIONALITY_CONTROLLER_CREATE,
    GSP_NATIONALITY_CONTROLLER_UPDATE,
    GSP_NATIONALITY_CONTROLLER_DELETE,
    LINK_ABS_COUNTRY_TO_CORE_COUNTRY,
    LINK_ABS_DISTRICT_TO_CORE_DISTRICT,
    LINK_ABS_NATION_TO_CORE_NATIONALITY,
    LINK_ABS_PARTY_TO_CORE_PARTY,
    LINK_ABS_REGION_TO_CORE_REGION,
    LINK_ABS_POSITION_TO_CORE_POSITION,
    STAFF_CONTROLLER_CREATE,
    STAFF_CONTROLLER_UPDATE,
    STAFF_CONTROLLER_DELETE,
    STAFF_CONTROLLER_CLOSE,
    POSITION_CONTROLLER_CREATE,
    POSITION_CONTROLLER_UPDATE,
    POSITION_CONTROLLER_DELETE,
    IABS_LOAD_COUNTRIES,
    IABS_LOAD_DISTRICTS,
    IABS_LOAD_NATIONS,
    IABS_LOAD_PARTIES,
    IABS_LOAD_REGIONS,
    DIPLOMA_QUALIFICATION_CREATE,
    DIPLOMA_QUALIFICATION_UPDATE,
    DIPLOMA_QUALIFICATION_DELETE,
    EDUCATIONAL_INSTITUTION_CREATE,
    EDUCATIONAL_INSTITUTION_UPDATE,
    EDUCATIONAL_INSTITUTION_DELETE,
    FACULTY_CREATE,
    FACULTY_UPDATE,
    FACULTY_DELETE,
    FORM_STUDY_CREATE,
    FORM_STUDY_UPDATE,
    FORM_STUDY_DELETE,
    RELATIVES_CREATE,
    RELATIVES_UPDATE,
    RELATIVES_DELETE,
    SPECIALITY_CREATE,
    SPECIALITY_UPDATE,
    SPECIALITY_DELETE,
    COMPANY_CREATE,
    COMPANY_UPDATE,
    COMPANY_DELETE,
    EDUCATION_CREATE,
    EDUCATION_CREATE_BY_USER,
    EDUCATION_UPDATE,
    EDUCATION_DELETE,
    GET_FORMS_WITH_FIELDS,
    TASKS_USER_FORM_SET_VALUES_AND_RETURN_VALUES,
    TASKS_USER_FORM_SET_VALUES_AND_RETURN_VALUES_COMPLETE,
    EMPLOYEE_REGISTER_REQUEST_CREATE,
    EMPLOYEE_REGISTER_REQUEST_UPDATE,
    EMPLOYEE_REGISTER_REQUEST_DELETE,
    CREATE_NEW_DOCUMENT,
    EMPLOYEE_REQUEST_CONFIRM,
    CREATE_RECRUITMENT,
    EMPLOYEE_CREATE,
    EMPLOYEE_UPDATE,
    EMPLOYEE_DELETE,
    EMPLOYEE_CREATE_BY_DOCUMENT,
    EMPLOYEE_EDUCATION_CREATE,
    EMPLOYEE_EDUCATION_UPDATE,
    EMPLOYEE_EDUCATION_DELETE,
    EMPLOYEE_RELATION_CREATE,
    EMPLOYEE_RELATION_UPDATE,
    EMPLOYEE_RELATION_DELETE,
    CREATE_STRUCTURE_VERSION,
    EMPLOYEE_RELATIVES_CREATE,
    EMPLOYEE_RELATIVES_UPDATE,
    EMPLOYEE_RELATIVES_DELETE,
    STRUCTURE_CHANGE_HIERARCHY,
    STRUCTURE_LINK_BATCH,
    STRUCTURE_ABS_SYNC,
    STRUCTURE_ABS_SYNC_FILIALS,
    EMPLOYEE_REFRESH_SERVICES_DATA,
    CREATE_STRUCTURE,
    RELOAD_EMPLOYEE_PROFILE_PHOTO,
    RELOAD_EMPLOYEE_INFO_FROM_IABS,
    ASYNC_VACCINE_CERTIFICATE,
    ASYNC_EMPLOYEE_RELATIVES,
    SET_STRUCTURE_TYPE_CHILD_ALL,
    ASYNC_EMPLOYEE_CONVICTION,
    ASYNC_EMPLOYEE_PSYCHO_INFO,
    ASYNC_EMPLOYEE_NARCO_INFO,
    ASYNC_EMPLOYEE_CV,
    ASYNC_WORK_REFERENCE,
    SET_STRUCTURE_HIERARCHY_AS_TEMPLATE,
    BUSINESS_PROCESS_CREATE,
    BUSINESS_PROCESS_UPDATE,
    BUSINESS_PROCESS_DELETE,
    DOCUMENT_PROCESS_CREATE,
    DOCUMENT_SIGN_PROCESS,
    VACANCY_PROCESS_START,
    POST_UPDATE_STRUCTURE,
    VACATION_GRAPHIC_START,
    SET_EXCEPTION_DAY,
    UPDATE_EXCEPTION_DAY,
    DELETE_EXCEPTION_DAY,
    DOCUMENT_SIGN_WITH_EIMZO_PROCESS,
    CREATE_AND_START_NEW_PROCESS,
    GENERATE_DOCS,
    UPLOAD_EMPLOYEE_FILE,
    UPLOAD_CANDIDATE_FILE,
    TEMPLATE_DOCUMENT_CUSTOM_VAR_STRUCTURE,
    MIGRATE_FILIAL_DATA
};
