const config = {
  APPNAME: "HRMS",
  ROUTE_BASENAME: "",
  API_ROOT: "http://172.28.7.100:14809/v1/",
  //API_ROOT: "http://172.28.0.118:8088/v1/",
  //BPMN_API_ROOT: "http://172.28.0.118:8090",
  BPMN_API_ROOT: "http://172.28.6.126:14820",
  //API_ROOT: window.location.origin + ':99/v1',
  //API_ROOT: http://172.28.5.55:28101,
  DEFAULT_LANG_CODE: "ru",
  PROJECT_ID: "HRMS",
  ROLES: {
    USER: "user",
    ADMIN: "admin",
    DIRECTOR: "Director",
    HEAD: "HEAD",
    CRM : "CRM",
    SUB_CHAIRMAN : "SUB_CHAIRMAN",
    ROLE__HR_DEPARTMENT : "ROLE__HR_DEPARTMENT",
    ROLE_CHAIRMAN : "ROLE_CHAIRMAN",
    ROLE__ASSISTANT_PERSONNEL_HEAD:"ROLE__ASSISTANT_PERSONNEL_HEAD",
    ROLE__HR_REGIONAL : "ROLE__HR_REGIONAL",
    ROLE__AUTONOMOUS_STRUCTURE : "ROLE__AUTONOMOUS_STRUCTURE",
    ROLE__HR_DEPARTMENT_HEAD :"ROLE__HR_DEPARTMENT_HEAD ",
    VACATION_GRAPHIC_PERMISSION:"VACATION_GRAPHIC_PERMISSION",
    DOCUMENT_ORDERS_PERMISSION:"DOCUMENT_ORDERS_PERMISSION",
    VACANCY_PERMISSION:"VACANCY_PERMISSION",
    CV_REQUEST_PERMISSION:"CV_REQUEST_PERMISSION"
  },
  TASK_USER_TYPE:'EMPLOYEE',
  TASK_USER_COLUMN:'employeeId'
};

export default config;
